Remove sed on sources.list (#76)
* Remove sed on sources.list

The file was removed from the container.

* Remove nvidia-cuda-dev

* Remove python2-dev

* Remove curl for now

src/utils/curl_stats/curl_la-curl_stats.lo
src/utils/curl_stats/curl_stats.c:128:5: error: 'CURLINFO_SIZE_UPLOAD' is deprecated: since 7.55.0.
Use CURLINFO_SIZE_UPLOAD_T [-Werror=deprecated-declarations]src/utils/curl_stats/curl_la-curl_stats.lo